### ISSUE TITLE
Optimist version

### ISSUE THREAD

**Issue by florianf** [paulovieira/tilelive-clima#1]
Hi,

thanks to your work, my TileMill for TileOven (https://github.com/florianf/tileoven) now works on Node 4. I also cherry picked some patches of your branch, thanks for that ;-)

Could you please update this package.json to also require optimist 0.6.0, this would fix TileMill test?

Regards,
Florian

**Comment by paulovieira** [comment]
Fantastic! I would never though someone out there would use this stuff :-)

I changed the names of the modules/repos to make them more explicit:
- `paulovieira/tilelive-clima`is now `paulovieira/tilelive` (and `package.json` as optimistic @0.6)  
- `paulovieira/millstone-clima` is now `paulovieira/millstone`
- `paulovieira/bones-clima` is now `paulovieira/bones`

Now they are also proper forks (with a reference to the original repo), which is useful to see the changes done to the original code.

I'll submit a pr to tileoven with these changes.

**Comment by pvml** [comment]
Also, note that in the `paulovieira/bones` repo we must use the 1.3 branch. So it should be `paulovieira/bones#1.3`
